### ISSUE TITLE
[Live Betting Test]: Could cheat and place test bets on winning team 1 and 1.5 goals while team 1 already scored 2-0

### ISSUE THREAD

**Issue by layer-0** [Azuro-protocol/Live-Betting-Bug-Report#19]
### Testing Scenario Conducted

Cheat Bet

### Test Description

On 03/03/2024 could made these test bets on win and over 1.5 goals while team was already leading with 2-0.

![-](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/38886361/298447c9-0bb5-47f4-9281-37adb79e7c47)
![99999](https://github.com/Azuro-protocol/Live-Betting-Bug-Report/assets/38886361/d2535bc8-c35b-4717-97db-6c1662efa0a6)

### Observed Behavior

Was able to complete some test bets.

### Expected Behavior

Had no expectations.

### Reproducibility of the Issue

Around 5 minutes after the 2-0 was made the market changed and was no more able to test bet it.

### Additional Information

Odds were also too high for team 1 when they were leading with 1-0 compared looking to the live stats.

**Comment by layer-0** [comment]
Hello @Avvrik , sorry, but why does Azuro request for testing here in Github if you just declare most as already reported or not an issue while its not already reported on Github clearly. So posting here is just a waste of time. Maybe announce that clearly on the site that no rewards are given and that it takes weeks to review too.

**Comment by Avvrik** [comment]
Hello, @layer-0, I'm deeply sorry the bugs aren't reviewed fast enough. We'll try to speed up the reviews! As for the assigned status, we're happy to reward people for their time spent on reporting the bugs. However, having a lot of bugs declined is very common in bug bounty programs because a lot of bugs are repeating each other, unfortunately (or maybe fortunately - because it means that everything else works fine). We also need to separate the bugs that concern Azuro as a smart contract infrastructure and the frontends issues. Azuro can fix only the former, but we cannot work with the bugs that refer to the frontends.
